apiVersion: v1
kind: Service
metadata:
    name: app-service
    namespace: build
spec:
    type: LoadBalancer
    selector:
        app: simple-app
    ports:
        - port: 8081
          name: web-interface
          targetPort: 8080
        - port: 50001
          name: testing
          targetPort: 50000